# build.toml
#
# Configuration for SPHERE-1 builds' common configuration
#
# (c) Andrew Shapton 2023
#
# Definition of the assembler in use

title = "Assembler Configuration TOML file"

[AssemblerConfig]
assembler       = "sbasm"                                                           # Name of assembler executable
assemblerDir    = "PATH/TO/ASSEMBLER/WITH/TRAILING/SLASH/"                          # Location of assembler