#!/bin/bash
# Set default build value
BUILD=`date +"%Y%m%d-%T" `
while getopts ":b:" option; do
   case $option in
      b) # Get Build Number
         BUILD=$OPTARG;;
   esac
done

V="VERSION:$BUILD"
LENGTH=${#V}
let SPC=(32-$LENGTH)/2
P=`printf "BUILD   .AZ  /"`
Q=`printf '%0.s!' $(seq 1 $SPC) | tr "!" " "`
FULLINE="$P$Q$V/"
echo "$FULLINE" > build.asm
../../SOFTWARE/asm/sbasm3/sbasm ttt.asm;
./CONVERT/convertEXE --input ttt.exe --prefix OX --base 0200 --title "OXO" --noheader  --cassette OXO
rm build.asm
cp ../../SOFTWARE/site/devsite/cassette_temp.js ../../SOFTWARE/site/devsite/cassette.js
cat ttt.exe.js >> ../../SOFTWARE/site/devsite/cassette.js
mv ttt.exe OUTPUT
mv ttt.exe.js OUTPUT
mv *.wav OUTPUT
