#!/bin/bash

#echo "DO NOT USE UNLESS YOU ARE ACTIVELY DEVELOPING THIS SOFTARE"
#echo "COMMENT OUT THE BELOW LINE IF YOU ARE"
#exit

# Set default build value
BUILD=`date +"%Y%m%d-%T" `

# For all location environment variables, ensure to use a trailing slash
# Set defaults for assembler and converter tools
SBASM_DIR=
CONVERTEXE_DIR=
SRC_DIR=
OUTPUT_DIR=

# Set location of SBASM (comment out if on search path)
SBASM_DIR=../../../SOFTWARE/asm/sbasm3/
# Set location of convertEXE (comment out if on search path)
CONVERTEXE_DIR=../TOOLS/CONVERT/
# Set location of output files (mandatory)
OUTPUT_DIR=OUTPUT/
# Set location of source files
SRC_DIR=src/


while getopts ":b:" option; do
   case $option in
      b) # Get Build Number
         BUILD=$OPTARG;;
   esac
done

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
#echo $CURRENT_BRANCH
#echo $CURRENT_BRANCH | tr [A-Z] [a-z]

IFS='/' read -r -a array <<< "$CURRENT_BRANCH"
if [ "${array[0]}" = "RELEASE" ]
then 
   echo "RELEASE BRANCH - ${array[1]}"
   BUILD=${array[1]}
   echo $BUILD
else
   echo "FEATURE BRANCH - ${array[1]}"
fi

# Create dynamic build information
V="VERSION:$BUILD"
LENGTH=${#V}
let SPC=(32-$LENGTH)/2
P=`printf "BUILD   .AZ  /"`
Q=`printf '%0.s!' $(seq 1 $SPC) | tr "!" " "`
FULLINE="$P$Q$V/"
echo "$FULLINE" > ${SRC_DIR}build.asm
cd $SRC_DIR
# Assemble the code to produce an output file (ttt.exe) in raw executable format
${SBASM_DIR}sbasm ttt.asm     
cd - > /dev/null
# Convert raw executable into a virtual sphere-compatible set of javascript
# Convert cassette form into a .WAV file
${CONVERTEXE_DIR}convertEXE --input ${SRC_DIR}ttt.exe --prefix OX --base 0200 --title "OXO" --silent --noheader  --cassette ttt --vcass ttt
rm ${SRC_DIR}build.asm 2>/dev/null

cp ../../SOFTWARE/site/devsite/cassette_temp.js ../../SOFTWARE/site/devsite/cassette.js
cat ${SRC_DIR}ttt.exe.js >> ../../SOFTWARE/site/devsite/cassette.js 2>/dev/null
mv ${SRC_DIR}ttt.exe $OUTPUT_DIR 2>/dev/null
mv ${SRC_DIR}ttt.exe.js $OUTPUT_DIR 2>/dev/null
mv *.wav $OUTPUT_DIR 2>/dev/null
mv *.cassette $OUTPUT_DIR 2>/dev/null
